### ISSUE TITLE
Exception in react-hotkeys-hook when selecting from previous entered values of an input element

### ISSUE THREAD

**Issue by rwollgar** [JohannesKlauss/react-hotkeys-hook#836]
Using 4.0.2 of react-hotkeys-hook
the hook has "enableOnFormTags" set to true
react 18.2

Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'toLocaleLowerCase')
    at Je (c:\gitrepos\zendesk-billing-app-v2\node_modules\react-hotkeys-hook\dist\index.js:1:16631)
    at <anonymous> (c:\gitrepos\zendesk-billing-app-v2\node_modules\react-hotkeys-hook\dist\index.js:1:20455)
    at <anonymous> (c:\gitrepos\zendesk-billing-app-v2\node_modules\react-hotkeys-hook\dist\index.js:1:20438)
    at <anonymous> (c:\gitrepos\zendesk-billing-app-v2\node_modules\react-hotkeys-hook\dist\index.js:1:20681)
Je @ c:\gitrepos\zendesk-billing-app-v2\node_modules\react-hotkeys-hook\dist\index.js:1:16631
<anonymous> @ c:\gitrepos\zendesk-billing-app-v2\node_modules\react-hotkeys-hook\dist\index.js:1:20455
<anonymous> @ c:\gitrepos\zendesk-billing-app-v2\node_modules\react-hotkeys-hook\dist\index.js:1:20438
<anonymous> @ c:\gitrepos\zendesk-billing-app-v2\node_modules\react-hotkeys-hook\dist\index.js:1:20681
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at n (c:\gitrepos\zendesk-billing-app-v2\node_modules\react-hotkeys-hook\dist\index.js:1:19706)
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at n (c:\gitrepos\zendesk-billing-app-v2\node_modules\react-hotkeys-hook\dist\index.js:1:19706)
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at n (c:\gitrepos\zendesk-billing-app-v2\node_modules\react-hotkeys-hook\dist\index.js:1:19706)
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at n (c:\gitrepos\zendesk-billing-app-v2\node_modules\react-hotkeys-hook\dist\index.js:1:19706)
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at n (c:\gitrepos\zendesk-billing-app-v2\node_modules\react-hotkeys-hook\dist\index.js:1:19706)
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at n (c:\gitrepos\zendesk-billing-app-v2\node_modules\react-hotkeys-hook\dist\index.js:1:19706)
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at n (c:\gitrepos\zendesk-billing-app-v2\node_modules\react-hotkeys-hook\dist\index.js:1:19706)
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at n (c:\gitrepos\zendesk-billing-app-v2\node_modules\react-hotkeys-hook\dist\index.js:1:19706)
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at n (c:\gitrepos\zendesk-billing-app-v2\node_modules\react-hotkeys-hook\dist\index.js:1:19706)
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at n (c:\gitrepos\zendesk-billing-app-v2\node_modules\react-hotkeys-hook\dist\index.js:1:19706)
    

![image](https://user-images.githubusercontent.com/519440/200990475-3f581484-f0da-4aea-baf4-cb68fdb327e0.png)

**Comment by JohannesKlauss** [comment]
thanks for raising that issue. I'll try to come up with a fix.

**Comment by rwollgar** [comment]
Thanks. 
It looks like it's triggered for each character in the selected previous value.
